rollup doc update
weavedb/weavedb-docs pull request #21
Opened 2024-01-09 10:56 UTC by drumfeet

* add web console folder

* update quick-start.mdx

* rename get-started to development

* udpate path from get-started to web-console

* move schemas.mdx rules.mdx authentication.mdx to sdk folder

* update path to sdk folder

* add advanced folder

* add details for test locally

* add run-local-test.mdx

* draft run-rollup-node.mdx

* temporarily disable github actions

* update run-local-test.mdx

* add Tabs for yarn and npm command

* update run-local-test.mdx

* add run-rollup-node.mdx

* hide all breadcumb

* add development.mdx

* update run-rollup-node.mdx

* update next version

* update run-local-test.mdx

* update run-rollup-node.mdx

* udpate run-rollup-node.mdx

* add run-jots.mdx

* update run-rollup-node.mdx

* add advanced folder

* update run-jots.mdx

* add clone-the-repo.mdx

* change folder structure

* code refactor

* update run-local-test.mdx

* update folder path

* update rollup-node.mdx

* wip

* add run-explorer.mdx

* wip

* update overview.mdx

* wip

* update overview.mdx

* move run-explorer.mdx

* update run-rollup-node.mdx

* update overview.mdx

* update run-explorer.mdx

* update light-client.mdx

* remove grpc-node.mdx

* add fpjson.mdx

* update fpjson.mdx

* update fpjson.mdx

* update quick-start.mdx

* update overview.mdx

* update fpjson.mdx

* update fpjson.mdx

* update fpjson.mdx

* update run-jots.mdx

* update run-rollup-node.mdx

* moved fpjson 2.0 to a new directory

* update run-rollup-node.mdx

* update docs and version history to latest version 0.39

* wip

* wip

2024-01-10 05:05 UTC, ahmadmardeni1 requested changes
Everything looks good! Just some minor changes are needed @drumfeet. 

Also, can you remove all the hidden (not released) pages from this pull request? Let's review them separately when we add them in the future.

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/development.mdx
> +- [Git](https://git-scm.com/downloads)
Please add this to the "Clone the repo" page as "Before cloning the repo, make sure you have the following prerequisites".

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/development/clone-the-repo.mdx
> +[WeaveDB](https://github.com/weavedb/weavedb) is a monorepo that consists of Warp contracts, SDK, REPL, a web console, Jots (Social App) and many helper scripts.
Can you add links to each of Warp contracts, SDK, REPL, web console, and Jots

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/fpjson.mdx
> +FPJSON is a domain-specific language (DSL) for WeaveDB that facilitates the development of fully decentralized databases.
Please explain why they need FPJSON here "to execute js functions etc".

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/query-api/read-queries.mdx
> +- `endAfter` : Fetch documents until just after a specific value.
change to
- `startAt`: Start fetching documents from a specific value.
- `startAfter`: Fetch documents beginning immediately after a specific value.
- `endAt`: Fetch documents up to a specific value.
- `endAfter`: Fetch documents up to and including a specific value.

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/query-api/read-queries.mdx
> +#### Skip with specific start point
Skip with a specific starting point

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/query-api/read-queries.mdx
> +Manages the retrieval of documents in pages, facilitating the handling of large datasets.
Manages the retrieval of documents in pages, making it easier to handle large datasets.

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/query-api/write-queries.mdx
> +Adds a new document with the specified data to the given collection.
Adds a new document to the given collection.

We should avoid over-explaining.

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/query-api/write-queries.mdx
> +Sets the specified JSON data in a document within the given collection.
It is simpler just to say "Adds a new document to the given collection and allows you to choose its document ID."

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/query-api/write-queries.mdx
> +Updates a specific document within a collection with the provided data. This command only modifies existing documents and does not create new ones.
delete "with the provided data." We should avoid over-explaining.

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/query-api/write-queries.mdx
> +Relay a query, allowing for the execution of a signed operation with additional parameters. Useful for scenarios where you need to delegate the execution of a database operation, potentially with add
change to Relay a query allows for ....

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/quick-start.mdx
> +This guide shows you how to quickly set up the WeaveDB SDK, along with steps to add and read data from a database collection. To keep things simple, it skips out configurations such as data schema an
please remove this part

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/quick-start.mdx
> +Open a terminal, go to the root directory of your project, and execute one of the following commands to install WeaveDB.
change to "Execute one of the following commands in the root directory of your project."

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/quick-start.mdx
> +Begin using WeaveDB by importing the appropriate module for your development environment.
please revert this back to one section "Initialize WeaveDB" and delete the explanation. It is simpler.

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/quick-start.mdx
> +Insert a new document into the database collection by calling `add` on the instance, passing in the data and the collection name.
not sure this explanation is needed. maybe just add a simple comment to the code sample below explaining the parameters?

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/quick-start.mdx
> +Fetch all documents from the database collection by calling `get` on the instance, passing in the collection name.
Same here, not needed. We have a comment below covering enough.

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/sdk/crons.mdx
> +`if` can create a conditional statement. If the second item evaluates `true` it executes the third item.
minor comma 
`if` can create a conditional statement. If the second item evaluates `true`, it executes the third item.

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/sdk/crons.mdx
> +Likewise, `ifelse` can have the forth item to execute in case the second item evaluates `false`.
Likewise, `ifelse` will execute the fourth item in case the second item evaluates `false`.

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/sdk/crons.mdx
> +  ["update", [{age: 40}, "people", "Bob"]] // execute if false
executed*

2024-01-10 05:05 UTC, ahmadmardeni1 commented on pages/sdk/crons.mdx
> +Cron executions are recorded to contract when someone executes a write query, which means if no one executes anything for a long time, cron jobs can pile up and slow down every read query. In such ca
Cron executions are recorded to the contract when someone executes a write query, which means if no one executes anything for a long time, cron jobs can pile up and slow down every read query. In such cases, you could execute the `tick()` query to record cron executions.

2024-01-10 07:49 UTC, drumfeet commented
> Everything looks good! Just some minor changes are needed @drumfeet.
> 
> Also, can you remove all the hidden (not released) pages from this pull request? Let's review them separately when we add them in the future.

I applied the requested changes and sent you a re-review. I will remove the hidden pages in the next commit

2024-01-12 05:04 UTC, ahmadmardeni1 reviewed
Everything else looks good! Just a couple of minor edits and remove the hidden files then we can merge it.

2024-01-12 05:04 UTC, ahmadmardeni1 commented on pages/fpjson.mdx
> +FPJSON is a domain-specific language (DSL) for WeaveDB that facilitates the development of fully decentralized databases. It enables advanced and composable functional programming in an easily unders
Please change to for simplicity: FPJSON is a domain-specific language (DSL) developed by WeaveDB to enable advanced and composable functional programming in an easily understandable JSON format.
For reference, see https://fpjson.weavedb.dev

2024-01-12 05:04 UTC, ahmadmardeni1 commented on pages/query-api/read-queries.mdx
> +- `endAfter` : Fetch documents up to and including a specific value.
btw does `endAt` include the specific value? and does `endAfter` include the value after the specified one?

if no, keep it as it is. If yes, please change to:

- `endAt`: Fetch documents up to and including a specific value.
- `endAfter`: Fetch documents up to, including, and the one after a specific value.

2024-01-12 05:04 UTC, ahmadmardeni1 commented on pages/sdk/crons.mdx
> +`if` can create a conditional statement. If the second item evaluates `true`, it executes the third item.
`if` creates a conditional statement. If the second item evaluates `true`, it executes the third item.

2024-01-12 05:31 UTC, ahmadmardeni1 commented on pages/sdk/version.mdx
> +- Fix nexted triggers
is this nexted or nested?

2024-01-12 13:54 UTC, drumfeet commented on pages/query-api/read-queries.mdx
> +- `endAfter` : Fetch documents up to and including a specific value.
Yes to both. Will apply the change

2024-01-12 13:54 UTC, drumfeet commented on pages/sdk/version.mdx
> +- Fix nexted triggers
nested

2024-01-12 14:03 UTC, drumfeet commented
> Everything else looks good! Just a couple of minor edits and remove the hidden files then we can merge it.

Got this. All requests are now applied. I think we can merge and deploy now.

2024-01-13 03:05 UTC, ahmadmardeni1 commented
why did you close the PR? @drumfeet yup it is read

2024-01-13 13:25 UTC, drumfeet commented
Sorry. I might have accidentally clicked the wrong button. Will reopen and merge it

2024-01-14 01:40 UTC, merged